[workspace]
members = ["pfetch-extractor", "pfetch-logo-parser"]

[package]
name = "pfetch"
version = "3.0.1"
edition = "2021"
authors = ["Gobidev"]
description = "A rewrite of the pfetch system information tool"
repository = "https://github.com/Gobidev/pfetch-rs"
license = "MIT"
keywords = ["fetch", "pfetch", "cli", "system"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pfetch-logo-parser = { path = "./pfetch-logo-parser", version = "0.2.0" }
pfetch-extractor = { path = "./pfetch-extractor", version = "0.2.5" }
dotenvy = "0.15.6"
shellexpand = "3"
glob = "0.3.1"
which = "8"
libmacchina = "8.1.0"
crossterm = "0.28.1"
os-release = "0.1.0"
unicode-width = "0.2.0"
# static sqlite: avoids loading libsqlite3.so at startup
sqlite3-src = { version = "0.6.1", features = ["bundled"] }

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
